loss_config:
  l2_reg: 0.001
  entropy_weight: 0.0
  mag_weight: 0.0
  clip_target: false
  downweight_clipped: 1.0
  noncanon_weight: 0.0
  canon_weight: 0.0
  canon_usage_weight: 0.0
  helix_weight: 0.0
  eps: 1.0e-06
train_config:
  freeze_nc: false
  loop_pen: false
  h: 4
  lr: 0.01
  steps: 6000
  examples_per_step: 5
  val_examples_per_step: 5
  patience_warmup: 5
  patience: 10
