train_file: ../data/2A3/TRAIN/data.csv
val_file: ../data/2A3/VALIDATION/data.csv
loss_config:
  l2_reg: 0.0001
  entropy_weight: 0.0
  mag_weight: 0.0
  clip_target: true
  downweight_clipped: 0.5
  noncanon_weight: 0.0
  canon_weight: 0.0
  canon_usage_weight: 0.0
  helix_weight: 0.0
  eps: 1.0e-06
train_config:
  h: 3
  lr: 0.01
  steps: 7000
  examples_per_step: 50
  val_examples_per_step: 50
  patience_warmup: 30
  patience: 60
